# Generated by Django 4.0.5 on 2022-06-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('FR', 'French'), ('EN', 'English'), ('SL', 'Slovenian'), ('CR', 'Croatian')], max_length=5)),
                ('content', models.CharField(max_length=150)),
                ('diff', models.IntegerField(choices=[('1', 'New'), ('2', 'Med'), ('3', 'Inte'), ('4', 'Exp'), ('5', 'Perf')])),
                ('context_text', models.CharField(choices=[('rt', 'Restaurant'), ('tx', 'Taxi'), ('br', 'Bar'), ('', 'Rencontre')], max_length=500)),
                ('to_learn', models.BooleanField(default=False)),
                ('last_learn', models.DateField(blank=True, null=True)),
                ('skill', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
