# Generated by Django 4.0.5 on 2022-06-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='diff',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Med'), ('3', 'Inte'), ('4', 'Exp'), ('5', 'Perf')], max_length=2),
        ),
    ]
