# Generated by Django 4.0.5 on 2022-06-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseList', '0002_alter_phrase_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='context_text',
        ),
        migrations.AlterField(
            model_name='phrase',
            name='diff',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Beg'), ('3', 'Mid'), ('4', 'Flu'), ('5', 'Exp')], max_length=5),
        ),
    ]
