# Generated by Django 4.0.5 on 2022-06-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseList', '0003_remove_phrase_context_text_alter_phrase_diff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('source_language', models.CharField(choices=[('FR', 'French'), ('EN', 'English'), ('SL', 'Slovenian'), ('CR', 'Croatian')], max_length=5)),
                ('target_language', models.CharField(choices=[('FR', 'French'), ('EN', 'English'), ('SL', 'Slovenian'), ('CR', 'Croatian')], max_length=5)),
                ('dicty', models.JSONField(default='')),
            ],
        ),
    ]
