# Generated by Django 4.0.5 on 2022-06-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseList', '0004_dicty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicty',
            name='dicty',
        ),
        migrations.AddField(
            model_name='phrase',
            name='context',
            field=models.CharField(choices=[('Restaurant_bar', 'Restaurant'), ('Presentation', 'Presentation'), ('Salutation', 'Salutation'), ('Numbers', 'Numbres'), ('Direction', 'Direction'), ('Remerciement', 'Remerciement'), ('time', 'Time'), ('GG', 'General')], default='GG', max_length=500),
        ),
    ]
