# Generated by Django 4.0.5 on 2022-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseList', '0005_remove_dicty_dicty_phrase_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicty',
            name='dicty',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='phrase',
            name='traductions',
            field=models.ManyToManyField(blank=True, to='phraseList.phrase'),
        ),
    ]
