# Generated by Django 4.0.5 on 2022-06-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseList', '0007_remove_dicty_dicty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicty',
            name='source_phrases',
            field=models.ManyToManyField(to='phraseList.phrase'),
        ),
    ]
